"""add Genre model

Revision ID: 53db5ec167b1
Revises: 6657798a4eec
Create Date: 2025-05-07 17:00:37.645648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53db5ec167b1'
down_revision = '6657798a4eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
